In [2]:
import pandas as pd

In [3]:
# reads csv file
df = pd.read_csv('players_20.csv')
# set index
df.set_index('short_name',inplace = True)
# selecet columns
df = df[['long_name','age','dob','height_cm','weight_kg','nationality','club']]

In [4]:
# show Dataframe
df

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,170,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

# 1 Set value to one cell

In [5]:
# update L.Messi height
df.loc['L. Messi','height_cm'] = 175

In [6]:
# Show dataframe
df

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,175,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,187,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,175,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,188,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,175,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,186,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,177,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,186,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,185,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,182,78,China PR,Hebei China Fortune FC

# 2 Set value to entire column

In [7]:
# set height of all player to 190
df.loc[:, 'height_cm'] = 190

In [8]:
# show dataframe 
df

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32,1987-06-24,190,72,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,1985-02-05,190,83,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27,1992-02-05,190,68,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26,1993-01-07,190,87,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28,1991-01-07,190,74,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22,1997-03-10,190,79,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22,1997-01-01,190,66,China PR,Shanghai SIPG FC
Zhang Wei,张威,19,2000-05-16,190,75,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18,2000-08-02,190,74,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,潘喜明,26,1993-01-11,190,78,China PR,Hebei China Fortune FC

# 3 Set value to entire row

In [18]:
# get all column that correspond to player ranked last in fifa
import numpy as np
df.iloc[-1, :] = np.nan

In [12]:
# set null values to all columns that corresponds to player ranked last 
df.iloc[-1, :] = 0

In [19]:
df

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32.0,1987-06-24,190.0,72.0,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34.0,1985-02-05,190.0,83.0,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27.0,1992-02-05,190.0,68.0,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26.0,1993-01-07,190.0,87.0,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28.0,1991-01-07,190.0,74.0,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22.0,1997-03-10,190.0,79.0,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22.0,1997-01-01,190.0,66.0,China PR,Shanghai SIPG FC
Zhang Wei,张威,19.0,2000-05-16,190.0,75.0,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18.0,2000-08-02,190.0,74.0,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# 4 Set value to Multiple cells

In [25]:
# Set value for all items matching the list of labels
df.loc[['L. Messi', 'Cristiano Ronaldo'], ['height_cm']] = 175

In [26]:
# show dataframe
df

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32.0,1987-06-24,175.0,72.0,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34.0,1985-02-05,175.0,83.0,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,27.0,1992-02-05,190.0,68.0,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,26.0,1993-01-07,190.0,87.0,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,28.0,1991-01-07,190.0,74.0,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,22.0,1997-03-10,190.0,79.0,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,22.0,1997-01-01,190.0,66.0,China PR,Shanghai SIPG FC
Zhang Wei,张威,19.0,2000-05-16,190.0,75.0,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,18.0,2000-08-02,190.0,74.0,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# 5 Set value for rows matching a condition

In [27]:
# set value for rows matching a condition 
columns = ['age', 'dob', 'height_cm', 'weight_kg']
df.loc[df['height_cm'] > 180,columns] = 0

In [28]:
# show dataframe
df

,long_name,age,dob,height_cm,weight_kg,nationality,club
short_name,,,,,,,
L. Messi,Lionel Andrés Messi Cuccittini,32.0,1987-06-24,175.0,72.0,Argentina,FC Barcelona
Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34.0,1985-02-05,175.0,83.0,Portugal,Juventus
Neymar Jr,Neymar da Silva Santos Junior,0.0,0,0.0,0.0,Brazil,Paris Saint-Germain
J. Oblak,Jan Oblak,0.0,0,0.0,0.0,Slovenia,Atlético Madrid
E. Hazard,Eden Hazard,0.0,0,0.0,0.0,Belgium,Real Madrid
...,...,...,...,...,...,...,...
Shao Shuai,邵帅,0.0,0,0.0,0.0,China PR,Beijing Renhe FC
Xiao Mingjie,Mingjie Xiao,0.0,0,0.0,0.0,China PR,Shanghai SIPG FC
Zhang Wei,张威,0.0,0,0.0,0.0,China PR,Hebei China Fortune FC
Wang Haijian,汪海健,0.0,0,0.0,0.0,China PR,Shanghai Greenland Shenhua FC
Pan Ximing,NaN,NaN,NaN,NaN,NaN,NaN,NaN